### ISSUE TITLE
-

### ISSUE THREAD

**Issue by dy** [jonschlinkert/split-string#7]
Bundled `split-string` occupies 84kb. That includes buffer and other heavyweight dependencies. It would be really nice to reduce package size.

**Comment by jonschlinkert** [comment]
Why is `Buffer` included? Did you look at the tree? Maybe we can find that and eliminate it in whatever package is using it.

**Comment by dy** [comment]
Ok since that is unlikely a massive PR will be welcomed here, I've came up with an alternative implementation ....

**

Edited by Jon Schlinkert to remove link to duplicate package. I don't support this practice.

**Comment by jonschlinkert** [comment]
> Ok since that is unlikely a massive PR will be welcomed here

I'm not sure what that means, it sounds like something is being bundled that shouldn't be. I'd happily welcome a PR for that. 

At the same time, it sucks for the entire community when people publish duplicate libraries instead of trying to improve existing ones. Especially since your code is similar to previous versions of this package. Lame.

**Comment by jonschlinkert** [comment]
In retrospect, it seems clear that this was a spam to get attention for your new package, since 1) I don't see how Buffer is packaged in, perhaps it is, but that's easy to resolve, and 2) giving the timing of your issue and when you published the duplicate package, it seems clear that you were only trying to get attention for your duplicate.

**Comment by jonschlinkert** [comment]
@dy rarely does someone make their motivations so transparent. Your tweet just validated everything I just said.
